### ISSUE TITLE
Links don't work on "Customize a form using FormBuilder" file

### ISSUE THREAD

**Issue by irwinwilliams** [Microsoft/bot-framework-docs#7]
Hey, 
Several urls on this file, "https://github.com/Microsoft/bot-framework-docs/blob/master/articles/dotnet/bot-builder-dotnet-formflow-formbuilder.md" result in 404s.
It seems to be because of the use of ~/, for example the link for "Basic features of FormFlow" points to: 
https://github.com/Microsoft/bot-framework-docs/blob/master/articles/dotnet/~/dotnet/bot-builder-dotnet-formflow.md
but should really point to 
https://github.com/Microsoft/bot-framework-docs/blob/master/articles/dotnet/bot-builder-dotnet-formflow.md

**Comment by RobStand** [comment]
Hi @irwinwilliams! Thanks for reporting this. We will get a fix out for that very shortly.

**Comment by RobStand** [comment]
Hi @irwinwilliams, the usage of ~ in paths is intended for links in the published documentation. For example, the links you pointed out in the Markdown paths are rendered correctly in the published article at https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-formflow-formbuilder.
